In [1]:
import pandas as pd

In [2]:
aire = pd.read_csv("../dataset/air_condition.csv")

In [3]:
aire

,indicator_id,name,measure,geo_type_name,geo_join_id,data_value,geo_place_name,measure_info,time_period,message,start_date,unique_id
0,646,Outdoor Air Toxics - Benzene,Annual average concentration,CD,203.0,1.4,Morrisania and Crotona (CD3),Âµg/m3,2011,NaN,2011-01-01T00:00:00.000,227582
1,646,Outdoor Air Toxics - Benzene,Annual average concentration,CD,303.0,1.4,Bedford Stuyvesant (CD3),Âµg/m3,2011,NaN,2011-01-01T00:00:00.000,227594
2,646,Outdoor Air Toxics - Benzene,Annual average concentration,CD,503.0,1.1,Tottenville and Great Kills (CD3),Âµg/m3,2011,NaN,2011-01-01T00:00:00.000,227626
3,375,Nitrogen dioxide (NO2),Mean,UHF34,306308.0,32.9,Chelsea-Village,ppb,Annual Average 2012,NaN,2011-12-01T00:00:00.000,172709
4,375,Nitrogen dioxide (NO2),Mean,UHF34,203.0,22.9,Bedford Stuyvesant - Crown Heights,ppb,Annual Average 2012,NaN,2011-12-01T00:00:00.000,172687
...,...,...,...,...,...,...,...,...,...,...,...,...
18020,365,Fine particles (PM 2.5),Mean,CD,409.0,9.7,Kew Gardens and Woodhaven (CD9),mcg/m3,Annual Average 2011,NaN,2010-12-01T00:00:00.000,170332
18021,365,Fine particles (PM 2.5),Mean,CD,411.0,6.0,Bayside and Little Neck (CD11),mcg/m3,Annual Average 2020,NaN,2020-01-01T00:00:00.000,669964
18022,365,Fine particles (PM 2.5),Mean,CD,209.0,9.5,Parkchester and Soundview (CD9),mcg/m3,Annual Average 2012,NaN,2011-12-01T00:00:00.000,170361
18023,365,Fine particles (PM 2.5),Mean,CD,209.0,7.1,Parkchester and Soundview (CD9),mcg/m3,Summer 2022,NaN,2022-06-01T00:00:00.000,823179
18024,375,Nitrogen dioxide (NO2),Mean,CD,409.0,10.6,Kew Gardens and Woodhaven (CD9),ppb,Summer 2022,NaN,2022-06-01T00:00:00.000,826375

In [4]:
aire.columns

Index(['indicator_id', 'name', 'measure', 'geo_type_name', 'geo_join_id',
       'data_value', 'geo_place_name', 'measure_info', 'time_period',
       'message', 'start_date', 'unique_id'],
      dtype='object')

De las 12 columnas disponibles, decidimos quedarnos con las siguientes 9:
- Indicator ID
- Name
- measure_info
- geo_type_name
- geo_join_id
- geo_place_name
- time_period
- start_date
- data_value

In [5]:
aire.drop('measure', axis=1) # La columna "Measure" la eliminamos, porque no nos aporta información relevante para nuestro posterior análisis

,indicator_id,name,geo_type_name,geo_join_id,data_value,geo_place_name,measure_info,time_period,message,start_date,unique_id
0,646,Outdoor Air Toxics - Benzene,CD,203.0,1.4,Morrisania and Crotona (CD3),Âµg/m3,2011,NaN,2011-01-01T00:00:00.000,227582
1,646,Outdoor Air Toxics - Benzene,CD,303.0,1.4,Bedford Stuyvesant (CD3),Âµg/m3,2011,NaN,2011-01-01T00:00:00.000,227594
2,646,Outdoor Air Toxics - Benzene,CD,503.0,1.1,Tottenville and Great Kills (CD3),Âµg/m3,2011,NaN,2011-01-01T00:00:00.000,227626
3,375,Nitrogen dioxide (NO2),UHF34,306308.0,32.9,Chelsea-Village,ppb,Annual Average 2012,NaN,2011-12-01T00:00:00.000,172709
4,375,Nitrogen dioxide (NO2),UHF34,203.0,22.9,Bedford Stuyvesant - Crown Heights,ppb,Annual Average 2012,NaN,2011-12-01T00:00:00.000,172687
...,...,...,...,...,...,...,...,...,...,...,...
18020,365,Fine particles (PM 2.5),CD,409.0,9.7,Kew Gardens and Woodhaven (CD9),mcg/m3,Annual Average 2011,NaN,2010-12-01T00:00:00.000,170332
18021,365,Fine particles (PM 2.5),CD,411.0,6.0,Bayside and Little Neck (CD11),mcg/m3,Annual Average 2020,NaN,2020-01-01T00:00:00.000,669964
18022,365,Fine particles (PM 2.5),CD,209.0,9.5,Parkchester and Soundview (CD9),mcg/m3,Annual Average 2012,NaN,2011-12-01T00:00:00.000,170361
18023,365,Fine particles (PM 2.5),CD,209.0,7.1,Parkchester and Soundview (CD9),mcg/m3,Summer 2022,NaN,2022-06-01T00:00:00.000,823179
18024,375,Nitrogen dioxide (NO2),CD,409.0,10.6,Kew Gardens and Woodhaven (CD9),ppb,Summer 2022,NaN,2022-06-01T00:00:00.000,826375

In [6]:
aire = aire.drop('measure', axis=1)

In [13]:
aire["message"].isnull().sum()

18025

In [8]:
aire.drop('message', axis=1) # La columna "message" también la eliminamos porque sólo contiene nulos en su interior

,indicator_id,name,geo_type_name,geo_join_id,data_value,geo_place_name,measure_info,time_period,start_date,unique_id
0,646,Outdoor Air Toxics - Benzene,CD,203.0,1.4,Morrisania and Crotona (CD3),Âµg/m3,2011,2011-01-01T00:00:00.000,227582
1,646,Outdoor Air Toxics - Benzene,CD,303.0,1.4,Bedford Stuyvesant (CD3),Âµg/m3,2011,2011-01-01T00:00:00.000,227594
2,646,Outdoor Air Toxics - Benzene,CD,503.0,1.1,Tottenville and Great Kills (CD3),Âµg/m3,2011,2011-01-01T00:00:00.000,227626
3,375,Nitrogen dioxide (NO2),UHF34,306308.0,32.9,Chelsea-Village,ppb,Annual Average 2012,2011-12-01T00:00:00.000,172709
4,375,Nitrogen dioxide (NO2),UHF34,203.0,22.9,Bedford Stuyvesant - Crown Heights,ppb,Annual Average 2012,2011-12-01T00:00:00.000,172687
...,...,...,...,...,...,...,...,...,...,...
18020,365,Fine particles (PM 2.5),CD,409.0,9.7,Kew Gardens and Woodhaven (CD9),mcg/m3,Annual Average 2011,2010-12-01T00:00:00.000,170332
18021,365,Fine particles (PM 2.5),CD,411.0,6.0,Bayside and Little Neck (CD11),mcg/m3,Annual Average 2020,2020-01-01T00:00:00.000,669964
18022,365,Fine particles (PM 2.5),CD,209.0,9.5,Parkchester and Soundview (CD9),mcg/m3,Annual Average 2012,2011-12-01T00:00:00.000,170361
18023,365,Fine particles (PM 2.5),CD,209.0,7.1,Parkchester and Soundview (CD9),mcg/m3,Summer 2022,2022-06-01T00:00:00.000,823179
18024,375,Nitrogen dioxide (NO2),CD,409.0,10.6,Kew Gardens and Woodhaven (CD9),ppb,Summer 2022,2022-06-01T00:00:00.000,826375

In [14]:
aire = aire.drop('message', axis=1)

In [18]:
aire.drop('unique_id', axis=1) # La columna unique_id la eliminamos porque era un id unico de cada registro del dataset, no nos sirve para nuestro análisis posterior

,indicator_id,name,geo_type_name,geo_join_id,data_value,geo_place_name,measure_info,time_period,start_date
0,646,Outdoor Air Toxics - Benzene,CD,203.0,1.4,Morrisania and Crotona (CD3),Âµg/m3,2011,2011-01-01T00:00:00.000
1,646,Outdoor Air Toxics - Benzene,CD,303.0,1.4,Bedford Stuyvesant (CD3),Âµg/m3,2011,2011-01-01T00:00:00.000
2,646,Outdoor Air Toxics - Benzene,CD,503.0,1.1,Tottenville and Great Kills (CD3),Âµg/m3,2011,2011-01-01T00:00:00.000
3,375,Nitrogen dioxide (NO2),UHF34,306308.0,32.9,Chelsea-Village,ppb,Annual Average 2012,2011-12-01T00:00:00.000
4,375,Nitrogen dioxide (NO2),UHF34,203.0,22.9,Bedford Stuyvesant - Crown Heights,ppb,Annual Average 2012,2011-12-01T00:00:00.000
...,...,...,...,...,...,...,...,...,...
18020,365,Fine particles (PM 2.5),CD,409.0,9.7,Kew Gardens and Woodhaven (CD9),mcg/m3,Annual Average 2011,2010-12-01T00:00:00.000
18021,365,Fine particles (PM 2.5),CD,411.0,6.0,Bayside and Little Neck (CD11),mcg/m3,Annual Average 2020,2020-01-01T00:00:00.000
18022,365,Fine particles (PM 2.5),CD,209.0,9.5,Parkchester and Soundview (CD9),mcg/m3,Annual Average 2012,2011-12-01T00:00:00.000
18023,365,Fine particles (PM 2.5),CD,209.0,7.1,Parkchester and Soundview (CD9),mcg/m3,Summer 2022,2022-06-01T00:00:00.000
18024,375,Nitrogen dioxide (NO2),CD,409.0,10.6,Kew Gardens and Woodhaven (CD9),ppb,Summer 2022,2022-06-01T00:00:00.000

In [19]:
aire = aire.drop('unique_id', axis=1)

También, la columna "time_period" la voy a dividir en otras dos columnas, por un lado, una va a contener el año, y otra la información adicional de la fecha

In [20]:
# Función para extraer el año
def extract_year(text):
    import re
    match = re.search(r'\b\d{4}\b', text)
    return match.group(0) if match else None

# Función para extraer la descripción
def extract_description(text):
    import re
    match = re.search(r'\b\d{4}\b', text)
    if match:
        return text.replace(match.group(0), '').strip()
    else:
        return text

# Aplicar las funciones al DataFrame
aire['año'] = aire['time_period'].apply(extract_year)
aire['descripcion_temporal'] = aire['time_period'].apply(extract_description)

# Llenar valores nulos en la columna 'description' con una cadena vacía
aire['descripcion_temporal'] = aire['descripcion_temporal'].fillna('')

Compruebo los resultados

In [21]:
aire[["time_period", "año", 'descripcion_temporal']]

               time_period   año descripcion_temporal
0                     2011  2011
1                     2011  2011
2                     2011  2011
3      Annual Average 2012  2012       Annual Average
4      Annual Average 2012  2012       Annual Average
...                    ...   ...                  ...
18020  Annual Average 2011  2011       Annual Average
18021  Annual Average 2020  2020       Annual Average
18022  Annual Average 2012  2012       Annual Average
18023          Summer 2022  2022               Summer
18024          Summer 2022  2022               Summer

[18025 rows x 3 columns]

In [22]:
aire.drop("time_period",axis=1) # Elimino la columna time_period ya que pude hacerle una limpieza y obtener a partir de ella los datos útiles

,indicator_id,name,geo_type_name,geo_join_id,data_value,geo_place_name,measure_info,start_date,año,descripcion_temporal
0,646,Outdoor Air Toxics - Benzene,CD,203.0,1.4,Morrisania and Crotona (CD3),Âµg/m3,2011-01-01T00:00:00.000,2011,
1,646,Outdoor Air Toxics - Benzene,CD,303.0,1.4,Bedford Stuyvesant (CD3),Âµg/m3,2011-01-01T00:00:00.000,2011,
2,646,Outdoor Air Toxics - Benzene,CD,503.0,1.1,Tottenville and Great Kills (CD3),Âµg/m3,2011-01-01T00:00:00.000,2011,
3,375,Nitrogen dioxide (NO2),UHF34,306308.0,32.9,Chelsea-Village,ppb,2011-12-01T00:00:00.000,2012,Annual Average
4,375,Nitrogen dioxide (NO2),UHF34,203.0,22.9,Bedford Stuyvesant - Crown Heights,ppb,2011-12-01T00:00:00.000,2012,Annual Average
...,...,...,...,...,...,...,...,...,...,...
18020,365,Fine particles (PM 2.5),CD,409.0,9.7,Kew Gardens and Woodhaven (CD9),mcg/m3,2010-12-01T00:00:00.000,2011,Annual Average
18021,365,Fine particles (PM 2.5),CD,411.0,6.0,Bayside and Little Neck (CD11),mcg/m3,2020-01-01T00:00:00.000,2020,Annual Average
18022,365,Fine particles (PM 2.5),CD,209.0,9.5,Parkchester and Soundview (CD9),mcg/m3,2011-12-01T00:00:00.000,2012,Annual Average
18023,365,Fine particles (PM 2.5),CD,209.0,7.1,Parkchester and Soundview (CD9),mcg/m3,2022-06-01T00:00:00.000,2022,Summer
18024,375,Nitrogen dioxide (NO2),CD,409.0,10.6,Kew Gardens and Woodhaven (CD9),ppb,2022-06-01T00:00:00.000,2022,Summer

In [23]:
aire = aire.drop("time_period",axis=1)

# Renombrar columnas

In [24]:
aire.columns

Index(['indicator_id', 'name', 'geo_type_name', 'geo_join_id', 'data_value',
       'geo_place_name', 'measure_info', 'start_date', 'año',
       'descripcion_temporal'],
      dtype='object')

In [25]:
diccionario_para_renombrar = {'indicator_id':"id_indicador", 'name':"nombre_del_indicador", 'geo_type_name':"tipo_geografico", 'geo_join_id':"id_de_union_geografico", 'data_value':"valor_del_dato",
       'geo_place_name':"nombre_del_barrio", 'measure_info':"unidad_de_medida", 'start_date':"fecha_inicial"}

In [28]:
aire.rename(diccionario_para_renombrar, axis=1)

,id_indicador,nombre_del_indicador,tipo_geografico,id_de_union_geografico,valor_del_dato,nombre_del_barrio,unidad_de_medida,fecha_inicial,año,descripcion_temporal
0,646,Outdoor Air Toxics - Benzene,CD,203.0,1.4,Morrisania and Crotona (CD3),Âµg/m3,2011-01-01T00:00:00.000,2011,
1,646,Outdoor Air Toxics - Benzene,CD,303.0,1.4,Bedford Stuyvesant (CD3),Âµg/m3,2011-01-01T00:00:00.000,2011,
2,646,Outdoor Air Toxics - Benzene,CD,503.0,1.1,Tottenville and Great Kills (CD3),Âµg/m3,2011-01-01T00:00:00.000,2011,
3,375,Nitrogen dioxide (NO2),UHF34,306308.0,32.9,Chelsea-Village,ppb,2011-12-01T00:00:00.000,2012,Annual Average
4,375,Nitrogen dioxide (NO2),UHF34,203.0,22.9,Bedford Stuyvesant - Crown Heights,ppb,2011-12-01T00:00:00.000,2012,Annual Average
...,...,...,...,...,...,...,...,...,...,...
18020,365,Fine particles (PM 2.5),CD,409.0,9.7,Kew Gardens and Woodhaven (CD9),mcg/m3,2010-12-01T00:00:00.000,2011,Annual Average
18021,365,Fine particles (PM 2.5),CD,411.0,6.0,Bayside and Little Neck (CD11),mcg/m3,2020-01-01T00:00:00.000,2020,Annual Average
18022,365,Fine particles (PM 2.5),CD,209.0,9.5,Parkchester and Soundview (CD9),mcg/m3,2011-12-01T00:00:00.000,2012,Annual Average
18023,365,Fine particles (PM 2.5),CD,209.0,7.1,Parkchester and Soundview (CD9),mcg/m3,2022-06-01T00:00:00.000,2022,Summer
18024,375,Nitrogen dioxide (NO2),CD,409.0,10.6,Kew Gardens and Woodhaven (CD9),ppb,2022-06-01T00:00:00.000,2022,Summer

In [29]:
aire = aire.rename(diccionario_para_renombrar, axis=1)

Exporto el dataset ya transformado parcialmente

In [30]:
aire.to_csv("../Datasets/dataset_aire_post_etl_inicial.csv")